spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment-service?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    include: oauth
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  messaging:
    stomp:
      relay:
        host: localhost
        port: 61613
server:
  port: 8081

iamport:
  key: ${IAMPORT_KEY}
  secret: ${IAMPORT_SECRET}

logging:
  level:
    web: debug