spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment-service?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080

iamport:
  key: ${IAMPORT_KEY}
  secret: ${IAMPORT_SECRET}

