spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      uri: mongodb://root:root@localhost:27017/admin
      database: airline
      password: root
      authentication-database: admin
  datasource:
    url: jdbc:mysql://localhost:3307/airline?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    include: oauth
  rabbitmq:
    host: localhost
    port: 5672
    username: juju
    password: juju1209
    stream:
      virtual-host: /
    listener:
      simple:
        concurrency: 3
        max-concurrency: 10
  messaging:
    stomp:
      relay:
        host: localhost
        port: 61613
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
server:
  port: 8081
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
logging:
  level:
    web: debug